version: 2.1

orbs:
  test-orb: "bikerdave/test-orb@dev:first"

jobs:
  build:
    executor:
      name: "test-orb/php"

    steps:
      - checkout

      - test-orb/composer-install

      - test-orb/composer-install:
          path: "./public/concrete"