version: 2.1

orbs:
  test-orb: "bikerdave/test-orb@dev:first"

reattach: &reattach
  attach_workspace:
    at: ~/tmp/build


##
## JOBS
##
jobs:
  #
  fast-checkout:
    executor:
      name: "test-orb/php"
      tag: "7.1"

    steps:
      - test-orb/checkout-persist


  #
  build:
    executor:
      name: "test-orb/php"
      tag: "7.1"

    steps:
      # checkout source code
      - *reattach

      #
      - restore_cache:
          keys:
            - composer-project-v1-{{ checksum "composer.json" }}
            - composer-project-v1-
      - test-orb/composer-install
      - save_cache:
          paths:
            - ./vendor
            - ./public/packages/d_p_*
          key: composer-project-v1-{{ checksum "composer.json" }}

      #- test-orb/composer-install:
          #path: "./public/concrete"
          #scope: "concrete"
  
  #
  deploy:
    executor:
      name: "test-orb/php"
      tag: "7.1"

    steps:
      # checkout source code
      - *reattach

      - run: echo Hello World


##
## WORKFLOWS
##
workflows:
  version: 2

  # build workflow
  build-and-deploy:
    jobs:
      # default jobs
      - fast-checkout
      - build:
          requires:
            - fast-checkout

      # staging deploy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop

      # production deploy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
