version: 2.1

orbs:
  test-orb: bikerdave/test-orb@dev:first

jobs:
  build:
    machine: true
    
    steps:
      - test-orb/hello:
          username: 'JON'

      - test-orb/composer-install

      - test-orb/composer-install:
          path: './public/concrete'