version: 2.1

orbs:
  test-orb: "bikerdave/test-orb@dev:first"

fast-checkout: &fast-checkout
  attach_workspace:
    at: ~/tmp/build


##
## JOBS
##
jobs:
  #
  build:
    executor:
      name: "test-orb/php"

    steps:
      #
      - *fast-checkout

      #
      - restore_cache:
          keys:
            - composer-project-v1-{{ checksum "composer.json" }}
            - composer-project-v1-
      - test-orb/composer-install
      - save_cache:
          paths:
            - ./vendor
            - ./public/packages/d_p_*
          key: composer-project-v1-{{ checksum "composer.json" }}

      #- test-orb/composer-install:
          #path: "./public/concrete"
          #scope: "concrete"
  
  #
  deploy:
    executor:
      name: "test-orb/php"

    steps:
      - *fast-checkout

      - run: echo Hello World


##
## WORKFLOWS
##
workflows:
  version: 2

  # build workflow
  build-and-deploy:
    jobs:
      # default jobs
      - test-orb/checkout
      - build:
          requires:
            - test-orb/checkout

      # staging deploy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop

      # production deploy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
