version: 2.1

orbs:
  test-orb: "bikerdave/test-orb@dev:first"

machine: &machine
  executor:
      name: "test-orb/php"
      tag: "7.1"

reattach: &reattach
  attach_workspace:
    at: ~/tmp/build


##
## JOBS
##
jobs:
  #
  build:
    <<: *machine

    steps:
      # checkout source code
      - checkout
      # - run: "rm -rf .git"

      # 
      - test-orb/npm-install

      #
      - test-orb/composer-project-install
      - test-orb/composer-concrete-install

      #
      - test-orb/persist
  
  #
  deploy:
    <<: *machine

    steps:
      - *reattach

      - run: echo Hello World


##
## WORKFLOWS
##
workflows:
  version: 2

  # build workflow
  build-and-deploy:
    jobs:
      # default job
      - build

      # staging deploy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop

      # production deploy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
