version: 2.1

orbs:
  test-orb: "bikerdave/test-orb@dev:first"

machine: &machine
  executor:
      name: "test-orb/php"
      tag: "7.1"


##
## JOBS
##
jobs:
  #
  build:
    <<: *machine

    steps:
      # checkout source code
      - checkout

      # 
      - test-orb/npm-install

      #
      - test-orb/composer-project-install

      #
      - test-orb/composer-concrete-install

      #
      - test-orb/persist
  
  #
  deploy-staging:
    <<: *machine

    steps:
      #
      - test-orb/deploy:
          ip: "123.456.789"
  
  #
  deploy-production:
    <<: *machine

    steps:
      #
      - test-orb/deploy:
          ip: "987.654.321"


##
## WORKFLOWS
##
workflows:
  version: 2

  # build workflow
  build-and-deploy:
    jobs:
      # default job
      - build

      # staging deploy
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - develop

      # production deploy
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only:
                - master
