version: 2.1

orbs:
  test-orb: "bikerdave/test-orb@dev:first"

jobs:
  jobo:
    executor:
      name: "test-orb/php"

    steps:
      - checkout

      - test-orb/composer-install
  
  jobt:
    executor:
      name: "test-orb/php"

    steps:
      - checkout

      - test-orb/composer-install:
          path: "./public/concrete"


workflows:
  version: 2.1
  build:
    jobs:
      - jobo:
          filters:
            branches:
              ignore:
                - develop
                - master


  build-additional:
    jobs:
      - jobo:
          filters:
            branches:
              only:
                - develop

      - jobt:
          requires:
            - jobo
          filters:
            branches:
              only:
                - develop
