version: 2.1

orbs:
  test-orb: "bikerdave/test-orb@dev:first"

fast-checkout: &fast-checkout
  attach_workspace:
    at: ~/tmp/build


##
## JOBS
##
jobs:
  #
  build:
    executor:
      name: "test-orb/php"

    steps:
      - *fast-checkout

      - test-orb/composer-install

      - test-orb/composer-install:
          path: "./public/concrete"
  
  #
  deploy:
    executor:
      name: "test-orb/php"

    steps:
      - *fast-checkout

      - run: echo Hello World


##
## WORKFLOWS
##
workflows:
  version: 2

  # build workflow
  build-stuff:
    jobs:
      - test-orb/temp

      - build:
          filters:
            branches:
              ignore:
                - develop
                - master

  # staging workflow
  build-deploy-staging:
    jobs:
      - test-orb/temp

      - build:
          filters:
            branches:
              only:
                - develop

      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop

  # live workflow
  build-deploy-production:
    jobs:
      - test-orb/temp

      - build:
          filters:
            branches:
              only:
                - develop

      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
